### ISSUE TITLE
Обратная связь по тестовому заданию

### ISSUE THREAD

**Issue by ViacheslavTarasov** [arivlav/testforispring#1]
Артём, привет!

Отлично, что сделал все пункты тестового задания. По результатам code review, есть несколько предложений, как улучшить реализацию. Рекомендовал бы внести следующие  изменения:

- [x] **1. Краткая инструкция в  readme**
https://github.com/arivlav/testforispring/blob/8aa50bd020bc4e24eb21a4ab37f849601221cec4/readme.md
Readme можно дополнить краткой инструкцией из нескольких пунктов о том, как локально запустить и проверить работу проекта

- [x] **2. Форматирование запроса**
https://github.com/arivlav/testforispring/blob/8aa50bd020bc4e24eb21a4ab37f849601221cec4/migrations/Version20210612054026.php#L23
Запрос на создание таблицы лучше отформатировать, т.к. объемные запросы в одну строку сложны для восприятия. Тот же запрос в таком виде читать проще:
```
CREATE TABLE task (
  id          INT AUTO_INCREMENT NOT NULL,
  description LONGTEXT           NOT NULL,
  status      INT                NOT NULL,
  PRIMARY KEY (id)
)
  DEFAULT CHARACTER SET utf8
  COLLATE `UTF8_unicode_ci`
  ENGINE = InnoDB
```

- [x] **3. Удалить лишний код в классе TaskRepository**
Остался закомментированный код, который стоит удалить
https://github.com/arivlav/testforispring/blob/8aa50bd020bc4e24eb21a4ab37f849601221cec4/src/Repository/TaskRepository.php#L26

- [x] **4. Роуты в  REST API**
https://github.com/arivlav/testforispring/blob/8aa50bd020bc4e24eb21a4ab37f849601221cec4/src/Controller/TaskController.php#L79
Подход REST API предполагает взаимодействие с ресурсами приложения. В нашем случае это tasks, который мы можем создавать, изменять, удалять и получать посредством использования протокола HTTP. Поэтому, если следовать best practices,  есть несколько моментов, которые нужно учесть:
а) Версия приложения в URL - /v1/tasks
б) Конечные точки в URL это существительные, не глаголы
    - создать задачу:  POST /tasks
    - удалить задачу:  DELETE /tasks/47
    - получить список задач: GET /tasks
    - изменить задачу PUT: /tasks/47

- [x] **5. Внедрить TaskRepository в TaskController**
Сейчас приходится извлекать репозиторий в каждом методе контроллера  $this->getDoctrine()->getRepository(Task::class); Вместо этого можно внедрить TaskRepository через конструктор  TaskController (сконфигурировать зависимости в config/services.yaml)

- [x] 6. **Перенести из TaskController в TaskRepository сохранение и удаление сущности Task**
https://github.com/arivlav/testforispring/blob/8aa50bd020bc4e24eb21a4ab37f849601221cec4/src/Controller/TaskController.php#L127-L128
В классе TaskRepository можно добавить соответствующие методы сохранения/удаления task. В качестве аргумента передается экземпляр Task, который удаляется при помощи EntityManager. Получим более лаконичный код в контроллере, детали реализации сохранения/удаления будут скрыты в репозитории

- [x] **7. Уменьшить дублирование кода в TaskController**
В каждом методе повторяется один и тот же код создания  экземпляров класса Response. Создание Response можно вынести в отдельный метод, который принимает payload и  httpcode

- [x] **8. Вынести значения статуса задачи в константы**
В методах TaskController, используются значения статуса 0 и 1. С одной стороны непонятно, что означают эти числа, с другой - при изменении значений, например с 0/1 на true/false придеться искать все места, где мы в коде указывали эти конкретные значения. Если же создать класс TaskStatus  с публичными константами COMPLETED, IN_PROGRESS, удасться при их использовании сделать код более читаемым и понятным, а при необходимости можно в одном месте заменить значения

Если возникнут какие-то вопросы, готов ответить

**Comment by arivlav** [comment]
Привет, Слава!

Всё переделал согласно твоим рекомендациям.

**Comment by ViacheslavTarasov** [comment]
Артём, 5 пункт можно реализовать еще лаконичнее)
Сейчас внедрение TaskRepository выполнено отдельно через сигнатуру каждого метода. Например https://github.com/arivlav/testforispring/blob/b36aa3962c858aae47e0116ced339259d2e4a8ff/src/Controller/TaskController.php#L39

При увеличении количества зависимостей такой подход приведёт к громозкости сигнатур методов. Если воспользоваться  внедрением зависимостей через конструктор класса TaskController методы получатся менее громоздкие

```
public function createTask(Request $request): JsonResponse 
    ...
    $this->validator->validate($task);
    ...
     $this->taskRepository->createUpdateTask($task);
    ...
```

**Comment by arivlav** [comment]
Применил конструктор) Это вещь!)
